// End-to-end replay: MCAP bag -> SonarCfarFrontend -> FactorBuilders ->
// PoseGraphProblem -> GaussNewtonSolver -> StateStore -> SubmapManager ->
// trajectory + ATE + RunManifest. This is the concrete proof that the
// layers described in the architecture design actually compose, run on
// synthetic data generated by apps/tools/synth_bag_gen (this machine has
// neither HoloOcean nor ROS2).
//
// v1 limitations, documented rather than hidden:
//  - No real reliability scheduler / AI information cap (section 8.4):
//    sqrt-information values below are fixed constants, not calibrated.
//  - Landmark association for the sonar range factor now goes through a
//    real SubmapManager::QueryNearestPoint() call (see the sonar block
//    below): a detection within kLandmarkGateM of an already-known
//    landmark reuses that landmark's stored position; a miss inserts a
//    brand new one. What's still v1 (per sonar_range_factor's documented
//    limitation): sonar range+bearing alone can't observe elevation, so a
//    newly-inserted landmark's z is a placeholder (level with the sensor)
//    that nothing later refines — no joint landmark estimation yet, and no
//    covariance-aware (Mahalanobis) gating, just a fixed Euclidean radius.
//  - Sonar: only the top-ranked DBSCAN cluster per SonarFrame is consumed
//    (schemas/proto/uw/domain/hypothesis.proto's documented v1 rule — the
//    wire contract keeps room for a multi-hypothesis consumer, this app
//    isn't one). synth_bag_gen emits one synthetic ping per target-in-range
//    rather than one ping covering all of them, so this doesn't lose
//    information in THIS demo's scenario, but it isn't a general multi-
//    target-per-ping model — see synth_bag_gen's own header for that
//    caveat.
//  - Layered config (defaults/rig/scenario/experiment, section 14.2) covers
//    solver options and factor sqrt-information constants via --experiment
//    (see uw::runtime::LoadExperimentConfig); it does NOT yet drive
//    frontend/factor_builder/map_backend SELECTION (config.sonar_frontend
//    etc. are read but not dispatched on) — this app still only knows the
//    one hardcoded pipeline (relative_pose_v1 + sonar_range_v1 + depth_v1).
//  - defaults.warmup_seconds (0 by default) keeps keyframes inside the
//    warmup window in the graph and dead-reckoned via relative-pose
//    factors, but withholds sonar-range/depth ("absolute reference")
//    factors for them until the window ends. kf0 stays the fixed anchor
//    regardless. See the warmup block below for why.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "uw/domain/domain.hpp"
#include "uw/estimation/gauss_newton_solver.hpp"
#include "uw/estimation/pose_graph_problem.hpp"
#include "uw/estimation/state_store.hpp"
#include "uw/evaluation/trajectory_metrics.hpp"
#include "uw/factor_builders/depth_factor_builder.hpp"
#include "uw/factor_builders/relative_pose_factor_builder.hpp"
#include "uw/factor_builders/sonar_range_factor_builder.hpp"
#include "uw/frontends/acoustic_optic_depth_fusion_frontend.hpp"
#include "uw/frontends/sonar_cfar_frontend.hpp"
#include "uw/frontends/stereo_optical_depth_frontend.hpp"
#include "uw/mapping/acoustic_optic_map_bridge.hpp"
#include "uw/mapping/submap_manager.hpp"
#include "uw/runtime/acoustic_optic_synchronizer.hpp"
#include "uw/runtime/config.hpp"
#include "uw/runtime/mcap_io.hpp"
#include "uw/runtime/run_manifest.hpp"
#include "uw/sensor_models/geometry.hpp"
#include "uw/sensor_models/sonar_beam_model.hpp"

using uw::sensor_models::Pose3;

namespace {

struct Options {
  std::string bag_path;
  std::string experiment_path;
  std::string out_prefix = "/tmp/replay_demo";
  int max_iterations = -1;  // -1 = "not set on CLI"; falls back to config/hardcoded default
};

std::string ToTumLine(double timestamp_s, const Pose3& pose) {
  std::ostringstream out;
  out.precision(9);
  out << timestamp_s << " " << pose.translation.x() << " " << pose.translation.y() << " "
      << pose.translation.z() << " " << pose.rotation.x() << " " << pose.rotation.y() << " "
      << pose.rotation.z() << " " << pose.rotation.w();
  return out.str();
}

}  // namespace

int main(int argc, char** argv) {
  Options opt;
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    auto next = [&]() -> std::string {
      if (i + 1 >= argc) {
        std::cerr << "missing value for " << arg << "\n";
        std::exit(1);
      }
      return argv[++i];
    };
    if (arg == "--bag") {
      opt.bag_path = next();
    } else if (arg == "--experiment") {
      opt.experiment_path = next();
    } else if (arg == "--out") {
      opt.out_prefix = next();
    } else if (arg == "--max-iterations") {
      opt.max_iterations = std::stoi(next());
    } else {
      std::cerr << "unknown argument: " << arg << "\n";
      return 1;
    }
  }
  if (opt.bag_path.empty()) {
    std::cerr << "usage: replay_demo --bag <path.mcap> [--experiment <path.yaml>] "
                 "[--out <prefix>] [--max-iterations N]\n";
    return 1;
  }

  // Layer 1: platform defaults (either from --experiment's defaults: layer,
  // or this struct's built-in values — same numbers previously hardcoded
  // as kRelativePoseSqrtInfo etc. below, now factored out to
  // uw::runtime::PlatformDefaultsConfig so they have exactly one
  // definition, in configs/defaults/platform.yaml).
  uw::runtime::PlatformDefaultsConfig defaults;
  bool write_run_manifest = true;
  // Only set when --experiment loads a rig with cameras — gates the new
  // acoustic-optic pass below so the no-experiment path (used by
  // tests/l2_replay/determinism_test.sh) is provably unchanged.
  std::optional<uw::domain::RigCalibrationSnapshot> rig;
  if (!opt.experiment_path.empty()) {
    const auto config = uw::runtime::LoadExperimentConfig(opt.experiment_path);
    defaults = config.defaults;
    write_run_manifest = config.write_run_manifest;
    if (config.rig.cameras_size() > 0) rig = config.rig;
    std::cout << "loaded experiment config: " << opt.experiment_path << " (sonar_frontend="
              << config.sonar_frontend << ", estimator_mode=" << config.estimator_mode << ")\n";
  }
  if (opt.max_iterations > 0) defaults.max_iterations = opt.max_iterations;  // CLI wins last

  // Warmup window (defaults.warmup_seconds, 0 = disabled): translate to a
  // keyframe-count cutoff using synth_bag_gen's fixed 5 Hz keyframe spacing
  // ("kf0", "kf1", ... one every kKeyframeIntervalS — same coupling the TUM
  // timestamp below already relies on). Keyframes inside the window still
  // enter the graph and still get relative-pose (dead-reckoning) factors —
  // dead reckoning through the warmup period is exactly what a real
  // estimator keeps doing while it isn't yet trusting absolute corrections
  // — but they do NOT get sonar-range or depth factors (the two "absolute
  // reference" factor types below skip them). This is the batch-pose-graph
  // analogue of "don't fuse absolute fixes until the VIO's bias has settled"
  // (see defaults.warmup_seconds' doc comment in runtime/include/uw/
  // runtime/config.hpp for where the idea came from).
  //
  // kf0 stays the fixed anchor regardless of warmup_seconds: re-anchoring
  // to a later keyframe would require knowing that keyframe's true x/y/yaw,
  // which nothing in this graph observes (x/y/yaw are genuine gauge freedom
  // — see below) — only kf0 gets to use Identity() for those because
  // synth_bag_gen places kf0 at the world-frame origin by construction, not
  // because "first keyframe" is special in general.
  constexpr double kKeyframeIntervalS = 0.2;  // matches synth_bag_gen's 5 Hz spacing
  const int warmup_keyframes = defaults.warmup_seconds > 0.0
                                    ? static_cast<int>(std::ceil(defaults.warmup_seconds / kKeyframeIntervalS))
                                    : 0;
  std::unordered_set<std::string> warmup_keyframe_ids;
  for (int i = 0; i < warmup_keyframes; ++i) warmup_keyframe_ids.insert("kf" + std::to_string(i));
  if (warmup_keyframes > 0) {
    std::cout << "warmup_seconds=" << defaults.warmup_seconds << " -> " << warmup_keyframes
              << " keyframes dead-reckoned only (no sonar/depth fusion)\n";
  }

  // Gauge choice for the fixed anchor keyframe "kf0": x/y/yaw are genuine
  // gauge freedom for a relative-pose + range-only graph (nothing observes
  // an absolute horizontal position or heading), so identity is a fine
  // arbitrary choice for those. z is NOT gauge freedom once a depth factor
  // is in the graph — the depth sensor gives every keyframe (including
  // kf0) an absolute reference. Fixing kf0's z at 0 while depth factors
  // pull every other keyframe toward -measured_depth creates a genuine
  // constraint conflict (this was found by running the demo: the solver
  // stalled and ATE was several meters, not the sub-decimeter error a
  // clean synthetic scenario with this little noise should produce).
  // Anchoring kf0's z from its own depth measurement keeps the fixed
  // keyframe consistent with the rest of the graph — this is independent of
  // warmup_seconds: it directly seeds the fixed vertex rather than adding a
  // depth factor, so it's not one of the "fusions" warmup gates.
  double kf0_z = 0.0;
  uw::runtime::ReadMcapMessages<uw::domain::MeasurementEvidence>(
      opt.bag_path, "/evidence/depth",
      [&](uint64_t, const uw::domain::MeasurementEvidence& evidence) {
        if (kf0_z != 0.0) return;  // already found
        if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) return;
        if (evidence.source_observations_size() == 0) return;
        if (evidence.source_observations(0).value() != "kf0") return;
        kf0_z = -uw::domain::GetPayload<uw::domain::PressureDepthMeasurement>(evidence).depth_m();
      });

  uw::estimation::PoseGraphProblem problem;
  Pose3 kf0_pose = Pose3::Identity();
  kf0_pose.translation.z() = kf0_z;
  problem.AddKeyframe("kf0", kf0_pose, /*fixed=*/true);

  // sqrt-information constants, from configs/defaults/platform.yaml via
  // --experiment (or PlatformDefaultsConfig's built-in fallback values if
  // --experiment wasn't passed). See file header limitation note: these
  // are still fixed constants, not a calibrated reliability scheduler.
  const double relative_pose_sqrt_info = defaults.default_sqrt_information.relative_pose;
  const double sonar_range_sqrt_info = defaults.default_sqrt_information.sonar_range;
  const double depth_sqrt_info = defaults.default_sqrt_information.depth;

  uw::factor_builders::RelativePoseFactorBuilder relative_pose_builder;
  uw::factor_builders::SonarRangeFactorBuilder sonar_range_builder;
  uw::factor_builders::DepthFactorBuilder depth_builder;

  // Online landmark store for the sonar range factor's data association
  // (see file header). All discovered landmarks live in one "landmarks"
  // bucket at a fixed Identity pose, since QueryNearestPoint/
  // WorldPointsForKeyframe already store/return world-frame points — see
  // algorithms/mapping/submap_manager. Declared here (not down by
  // StateStore below) because it needs to be live during the sonar
  // evidence pass, not just after solving.
  uw::mapping::SubmapManager submap_manager;
  submap_manager.UpdateKeyframePose("landmarks", Pose3::Identity());
  int next_landmark_id = 0;
  int num_landmarks_discovered = 0;

  int num_relative_pose_factors = 0;
  uw::runtime::ReadMcapMessages<uw::domain::MeasurementEvidence>(
      opt.bag_path, "/evidence/relative_pose",
      [&](uint64_t, const uw::domain::MeasurementEvidence& evidence) {
        if (!uw::domain::HasPayload<uw::domain::RelativePoseMeasurement>(evidence)) return;
        const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(evidence);
        const std::string from = measurement.from_keyframe().value();
        const std::string to = measurement.to_keyframe().value();
        if (!problem.HasKeyframe(from)) return;  // out-of-order/unexpected input: skip, don't guess

        const auto measured_relative = Pose3::FromProto(measurement.relative_pose());
        const auto dead_reckoned_initial_guess = problem.GetKeyframePose(from) * measured_relative;
        problem.AddKeyframe(to, dead_reckoned_initial_guess);

        uw::domain::FactorCandidate candidate;
        candidate.set_residual_model(uw::factor_builders::RelativePoseFactorBuilder::kResidualModel);
        candidate.set_proposed_noise(relative_pose_sqrt_info);
        auto block = relative_pose_builder.Build(candidate, evidence, {});
        if (block) {
          problem.AddResidualBlock(std::move(block), {from, to});
          ++num_relative_pose_factors;
        }
      });
  std::cout << "added " << num_relative_pose_factors << " relative-pose factors, "
            << problem.NumKeyframes() << " keyframes\n";

  // sonar_cfar_frontend params: same values as
  // algorithms/frontends/sonar_cfar_frontend/test/sonar_cfar_frontend_test.cpp's
  // synthetic fixture, which synth_bag_gen's BuildSyntheticSonarFrame
  // deliberately mirrors (background=5, target blob=200 intensity).
  uw::frontends::SonarCfarFrontendParams cfar_params;
  cfar_params.cfar.num_training_cells = 16;
  cfar_params.cfar.num_guard_cells = 4;
  cfar_params.cfar.probability_false_alarm = 1e-2;
  cfar_params.detector_threshold = 50;
  uw::frontends::SonarCfarFrontend sonar_frontend(cfar_params);

  int num_sonar_frames = 0;
  int num_sonar_factors = 0;
  uw::runtime::ReadMcapMessages<uw::domain::SonarFrame>(
      opt.bag_path, "/raw/sonar_frame", [&](uint64_t, const uw::domain::SonarFrame& frame) {
        ++num_sonar_frames;
        const std::string keyframe_id = frame.header().observation_id().value();
        if (!problem.HasKeyframe(keyframe_id)) return;
        if (warmup_keyframe_ids.count(keyframe_id)) return;  // dead-reckoning only during warmup

        // v1 rule (schemas/proto/uw/domain/hypothesis.proto, see file
        // header): only the top-ranked (largest-cluster) candidate is
        // consumed. candidates(0) is a full MeasurementEvidence, not just
        // the payload — reuse it as-is rather than re-wrapping via
        // domain::TopCandidate<T>(), which would discard evidence_id/
        // algorithm_version for no benefit here.
        const auto hypothesis_set = sonar_frontend.ProcessSonarFrame(frame);
        if (hypothesis_set.candidates_size() == 0) return;  // no detection above threshold
        const auto& evidence = hypothesis_set.candidates(0);
        if (!uw::domain::HasPayload<uw::domain::SonarRangeBearing>(evidence)) return;
        const auto& measurement = uw::domain::GetPayload<uw::domain::SonarRangeBearing>(evidence);

        // Real submap_manager query (see file header): project the
        // detection into world frame using the keyframe's CURRENT
        // (dead-reckoned, not yet optimized) pose estimate, then ask the
        // submap for an already-known landmark within kLandmarkGateM. A
        // hit reuses that landmark's stored position (stable across
        // repeated sightings, not re-derived from this noisier single
        // detection); a miss means this is a never-before-seen landmark,
        // which gets inserted so later sightings can match it.
        const auto current_pose = problem.GetKeyframePose(keyframe_id);
        const Eigen::Vector3d local_detection(measurement.range_m() * std::cos(measurement.bearing_rad()),
                                               measurement.range_m() * std::sin(measurement.bearing_rad()),
                                               0.0);  // sonar has no elevation — see file header
        const Eigen::Vector3d predicted_point_W = current_pose.Apply(local_detection);

        constexpr double kLandmarkGateM = 1.5;  // margin over expected dead-reckoning drift at these ranges
        const auto existing = submap_manager.QueryNearestPoint(predicted_point_W, kLandmarkGateM);
        Eigen::Vector3d landmark_W;
        if (existing.has_value()) {
          landmark_W = *existing;
        } else {
          landmark_W = predicted_point_W;
          uw::domain::MapEvidence landmark_evidence;
          landmark_evidence.mutable_evidence_id()->set_value("landmark_" + std::to_string(next_landmark_id++));
          landmark_evidence.mutable_keyframe_id()->set_value("landmarks");
          landmark_evidence.mutable_local_frame()->set_value("world");
          landmark_evidence.set_representation_type(uw::domain::MAP_REPRESENTATION_POINT_CLOUD);
          landmark_evidence.set_reintegration_policy(
              uw::domain::MapEvidence::REINTEGRATION_POLICY_TRANSFORM_ONLY);
          std::string bytes(3 * sizeof(float), '\0');
          auto* raw = reinterpret_cast<float*>(bytes.data());
          raw[0] = static_cast<float>(landmark_W.x());
          raw[1] = static_cast<float>(landmark_W.y());
          raw[2] = static_cast<float>(landmark_W.z());
          landmark_evidence.set_geometry_or_occupancy(bytes);
          submap_manager.AddMapEvidence(landmark_evidence);
          ++num_landmarks_discovered;
        }

        uw::domain::FactorCandidate candidate;
        candidate.set_residual_model(uw::factor_builders::SonarRangeFactorBuilder::kResidualModel);
        candidate.set_proposed_noise(sonar_range_sqrt_info);
        uw::measurement_api::FactorBuildContext context;
        context.nearby_points_W = {landmark_W};
        auto block = sonar_range_builder.Build(candidate, evidence, context);
        if (block) {
          problem.AddResidualBlock(std::move(block), {keyframe_id});
          ++num_sonar_factors;
        }
      });
  std::cout << "discovered " << num_landmarks_discovered << " landmarks via submap query\n";
  std::cout << "processed " << num_sonar_frames << " sonar frames (sonar_cfar_frontend) -> "
            << num_sonar_factors << " sonar range factors\n";

  int num_depth_factors = 0;
  uw::runtime::ReadMcapMessages<uw::domain::MeasurementEvidence>(
      opt.bag_path, "/evidence/depth",
      [&](uint64_t, const uw::domain::MeasurementEvidence& evidence) {
        if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) return;
        if (evidence.source_observations_size() == 0) return;
        const std::string keyframe_id = evidence.source_observations(0).value();
        if (!problem.HasKeyframe(keyframe_id)) return;
        if (warmup_keyframe_ids.count(keyframe_id)) return;  // dead-reckoning only during warmup

        uw::domain::FactorCandidate candidate;
        candidate.set_residual_model(uw::factor_builders::DepthFactorBuilder::kResidualModel);
        candidate.set_proposed_noise(depth_sqrt_info);
        auto block = depth_builder.Build(candidate, evidence, {});
        if (block) {
          problem.AddResidualBlock(std::move(block), {keyframe_id});
          ++num_depth_factors;
        }
      });
  std::cout << "added " << num_depth_factors << " depth factors\n";

  uw::estimation::GaussNewtonSolver solver;
  uw::estimation::GaussNewtonSolver::Options solver_options;
  solver_options.max_iterations = defaults.max_iterations;
  solver_options.initial_lambda = defaults.initial_lambda;
  const auto summary = solver.Solve(problem, solver_options);
  std::cout << "solver: " << summary.iterations << " iterations, cost " << summary.initial_cost
            << " -> " << summary.final_cost << (summary.converged ? " (converged)" : " (stalled)")
            << "\n";

  // StateStore wiring (submap_manager was declared earlier — it's already
  // been accumulating landmark evidence since the sonar pass above).
  uw::estimation::StateStore state_store;
  std::vector<uw::evaluation::TrajectoryPose> estimated_trajectory;

  for (int i = 0; i < static_cast<int>(problem.KeyframeOrder().size()); ++i) {
    const std::string& kf_id = problem.KeyframeOrder()[i];
    const auto pose = problem.GetKeyframePose(kf_id);

    uw::domain::StateSnapshot snapshot;
    snapshot.mutable_state_id()->set_value(kf_id);
    *snapshot.mutable_pose_wb() = pose.ToProto();
    snapshot.set_tracking_status(uw::domain::StateSnapshot::TRACKING_STATUS_TRACKING);
    state_store.Commit(snapshot);

    submap_manager.UpdateKeyframePose(kf_id, pose);

    const double timestamp_s = static_cast<double>(i) * kKeyframeIntervalS;
    estimated_trajectory.push_back({timestamp_s, pose});
  }

  // Acoustic-optic pass (only when --experiment loaded a rig with cameras):
  // per keyframe, run StereoOpticalDepthFrontend -> SonarCfarFrontend
  // (reused, same instance as the sonar pass above) ->
  // AcousticOpticDepthFusionFrontend::Fuse -> BuildMapEvidenceFromFusedDepth,
  // depositing a THIRD MapEvidence bucket into submap_manager (keyed per
  // keyframe, alongside the existing "landmarks" bucket) using the pose
  // ALREADY committed above. This never touches PoseGraphProblem/the solver
  // /ATE — dense depth does not become a new factor type (see this
  // integration's own plan doc for why that's explicitly out of scope).
  int num_keyframes_with_camera = 0;
  int num_acoustic_optic_accepted = 0;
  int num_acoustic_optic_ambiguous = 0;
  int num_acoustic_optic_conflict = 0;
  int num_acoustic_optic_rejected = 0;
  int num_map_evidence_points = 0;
  if (rig.has_value()) {
    auto keyframe_id_for_time = [&](const uw::domain::Stamp& capture_time) -> std::string {
      const double t_s = uw::domain::ToSeconds(capture_time);
      const int index = static_cast<int>(std::lround(t_s / kKeyframeIntervalS));
      return "kf" + std::to_string(index);
    };

    std::unordered_map<std::string, uw::domain::ImageFrame> left_by_kf, right_by_kf;
    std::unordered_map<std::string, uw::domain::SonarFrame> sonar_by_kf;
    uw::runtime::ReadMcapMessages<uw::domain::ImageFrame>(
        opt.bag_path, "/raw/camera/left", [&](uint64_t, const uw::domain::ImageFrame& f) {
          left_by_kf[keyframe_id_for_time(f.header().capture_time())] = f;
        });
    uw::runtime::ReadMcapMessages<uw::domain::ImageFrame>(
        opt.bag_path, "/raw/camera/right", [&](uint64_t, const uw::domain::ImageFrame& f) {
          right_by_kf[keyframe_id_for_time(f.header().capture_time())] = f;
        });
    uw::runtime::ReadMcapMessages<uw::domain::SonarFrame>(
        opt.bag_path, "/raw/sonar_frame", [&](uint64_t, const uw::domain::SonarFrame& f) {
          // v1 top-1 rule (see file header): keep the first sonar frame seen
          // per keyframe if more than one target was in range.
          const std::string kf_id = f.header().observation_id().value();
          if (sonar_by_kf.find(kf_id) == sonar_by_kf.end()) sonar_by_kf[kf_id] = f;
        });

    uw::frontends::StereoOpticalDepthFrontendParams stereo_params;
    uw::frontends::StereoOpticalDepthFrontend stereo_frontend(stereo_params);
    uw::frontends::AcousticOpticDepthFusionParams fusion_params;
    uw::frontends::AcousticOpticDepthFusionFrontend fusion_frontend(fusion_params);
    uw::mapping::AcousticOpticMapBridgeParams bridge_params;

    for (std::size_t kf_index = 0; kf_index < problem.KeyframeOrder().size(); ++kf_index) {
      const std::string& kf_id = problem.KeyframeOrder()[kf_index];
      auto left_it = left_by_kf.find(kf_id);
      auto right_it = right_by_kf.find(kf_id);
      if (left_it == left_by_kf.end() || right_it == right_by_kf.end()) continue;
      ++num_keyframes_with_camera;

      const auto sonar_it = sonar_by_kf.find(kf_id);
      const uw::domain::SonarFrame empty_sonar;
      uw::runtime::SynchronizerParams sync_params;
      const auto sync_bundle = uw::runtime::SynchronizeAcousticOptic(
          left_it->second, std::optional<uw::domain::ImageFrame>(right_it->second),
          sonar_it != sonar_by_kf.end() ? sonar_it->second : empty_sonar, *rig, sync_params);

      uw::measurement_api::CameraFrameBundle bundle;
      bundle.primary = left_it->second;
      bundle.secondary = right_it->second;
      const auto optical_evidence = stereo_frontend.Process(bundle, *rig);
      if (!optical_evidence.has_value()) continue;

      uw::domain::HypothesisSet sonar_hypotheses;
      if (sonar_it != sonar_by_kf.end()) {
        sonar_hypotheses = sonar_frontend.ProcessSonarFrame(sonar_it->second);
      }

      const double time_delta = sync_bundle.has_value() ? sync_bundle->max_pairwise_time_delta_s : 0.0;
      const auto fused_result = fusion_frontend.Fuse(sonar_hypotheses, *optical_evidence, *rig, time_delta);
      if (!fused_result.has_value()) continue;

      const auto& fused = uw::domain::GetPayload<uw::domain::FusedDepthMeasurement>(fused_result->fused_evidence);
      if (fused.associations_size() > 0) {
        switch (fused.associations(0).status()) {
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_ACCEPTED:
            ++num_acoustic_optic_accepted;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_AMBIGUOUS:
            ++num_acoustic_optic_ambiguous;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_CONFLICT:
            ++num_acoustic_optic_conflict;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_REJECTED:
            ++num_acoustic_optic_rejected;
            break;
          default:
            break;
        }
      }

      const uint64_t state_version = kf_index + 1;
      const auto map_evidence = uw::mapping::BuildMapEvidenceFromFusedDepth(
          fused_result->fused_evidence, *rig, bridge_params, kf_id, state_version);
      if (map_evidence.has_value()) {
        num_map_evidence_points +=
            static_cast<int>(map_evidence->geometry_or_occupancy().size() / (3 * sizeof(float)));
        submap_manager.AddMapEvidence(*map_evidence);
      }
    }
    std::cout << "acoustic-optic: " << num_keyframes_with_camera << " keyframes with camera data, "
              << num_acoustic_optic_accepted << " accepted, " << num_acoustic_optic_ambiguous
              << " ambiguous, " << num_acoustic_optic_conflict << " conflict, " << num_acoustic_optic_rejected
              << " rejected, " << num_map_evidence_points << " map evidence points added\n";
  }

  std::vector<uw::evaluation::TrajectoryPose> ground_truth_trajectory;
  uw::runtime::ReadMcapMessages<uw::domain::StateSnapshot>(
      opt.bag_path, "/gt/state", [&](uint64_t, const uw::domain::StateSnapshot& snapshot) {
        const auto pose = Pose3::FromProto(snapshot.pose_wb());
        const double timestamp_s = static_cast<double>(snapshot.capture_timestamp().seconds()) +
                                    static_cast<double>(snapshot.capture_timestamp().nanos()) * 1e-9;
        ground_truth_trajectory.push_back({timestamp_s, pose});
      });

  const auto ate = uw::evaluation::ComputeAte(estimated_trajectory, ground_truth_trajectory);
  std::cout << "ATE: rmse=" << ate.rmse_m << "m mean=" << ate.mean_m << "m max=" << ate.max_m
            << "m (" << ate.num_matched_poses << " matched poses)\n";

  {
    std::ofstream traj_out(opt.out_prefix + "_trajectory.tum");
    for (const auto& pose_entry : estimated_trajectory) {
      traj_out << ToTumLine(pose_entry.timestamp_s, pose_entry.pose_WB) << "\n";
    }
  }

  if (write_run_manifest) {
    uw::runtime::RunManifest manifest;
    manifest.run_id = "replay_demo_" + std::to_string(
                                            std::chrono::duration_cast<std::chrono::seconds>(
                                                std::chrono::system_clock::now().time_since_epoch())
                                                .count());
    manifest.dataset_or_scenario = opt.bag_path;
    manifest.simulator = "synthetic (apps/tools/synth_bag_gen)";
    std::ofstream manifest_out(opt.out_prefix + "_run_manifest.json");
    manifest_out << manifest.ToJson();
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum and " << opt.out_prefix
              << "_run_manifest.json\n";
  } else {
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum (run_manifest disabled by config)\n";
  }
  return 0;
}
