// End-to-end replay: MCAP bag -> SonarCfarFrontend -> FactorBuilders ->
// PoseGraphProblem -> GaussNewtonSolver -> StateStore -> SubmapManager ->
// trajectory + ATE + RunManifest. This is the concrete proof that the
// layers described in the architecture design actually compose, run on
// synthetic data generated by apps/synth_bag_gen.cpp (this machine has
// neither HoloOcean nor ROS2).
//
// v1 limitations, documented rather than hidden:
//  - No real reliability scheduler / learned-model information cap (section
//    8.4): sqrt-information values below are fixed constants, not a
//    calibrated reliability policy.
//  - Landmark association for the sonar range factor now goes through a
//    real SubmapManager::QueryNearestPoint() call (see the sonar block
//    below): a detection within kLandmarkGateM of an already-known
//    landmark reuses that landmark's stored position; a miss inserts a
//    brand new one. What's still v1 (per sonar_range_factor's documented
//    limitation): sonar range+bearing alone can't observe elevation, so a
//    newly-inserted landmark's z is a placeholder (level with the sensor)
//    that nothing later refines — no joint landmark estimation yet, and no
//    covariance-aware (Mahalanobis) gating, just a fixed Euclidean radius.
//  - Sonar: only the top-ranked DBSCAN cluster per SonarFrame is consumed
//    (schemas/proto/uw/domain/hypothesis.proto's documented v1 rule — the
//    wire contract keeps room for a multi-hypothesis consumer, this app
//    isn't one). synth_bag_gen emits one synthetic ping per target-in-range
//    rather than one ping covering all of them, so this doesn't lose
//    information in THIS demo's scenario, but it isn't a general multi-
//    target-per-ping model — see synth_bag_gen's own header for that
//    caveat.
//  - Layered config (defaults/rig/scenario/experiment, section 14.2) covers
//    solver options and factor sqrt-information constants via --experiment
//    (see uw::runtime::LoadExperimentConfig). estimator_mode and
//    landmark_detector genuinely dispatch (see the stereo_landmark_vo
//    block below); sonar_frontend/optical_frontend/map_backend still only
//    ever run one hardcoded implementation each (sonar_range_v1 +
//    depth_v1 + submap_point_cloud_v1) because no second implementation
//    exists yet — but as of ValidateExperimentConfigSelections(), naming
//    anything else in an experiment YAML fails the run at startup instead
//    of silently running that one pipeline anyway.
//  - defaults.warmup_seconds (0 by default) keeps keyframes inside the
//    warmup window in the graph and dead-reckoned via relative-pose
//    factors, but withholds sonar-range/depth ("absolute reference")
//    factors for them until the window ends. kf0 stays the fixed anchor
//    regardless. See the warmup block below for why.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <sys/utsname.h>

#ifdef UW_HAVE_CERES_SOLVER
#include "adapters/ceres/ceres_pose_graph_solver.hpp"
#endif
#include "application/event_pump.hpp"
#include "application/replay_input_accumulator.hpp"
#include "application/replay_pipeline.hpp"
#include "domain/domain.hpp"
#include "estimation/gauss_newton_solver.hpp"
#include "estimation/pose_graph_problem.hpp"
#include "estimation/state_store.hpp"
#include "evaluation/trajectory_metrics.hpp"
#include "factor_builders/depth_factor_builder.hpp"
#include "factor_builders/relative_pose_factor_builder.hpp"
#include "factor_builders/sonar_range_factor_builder.hpp"
#include "frontends/acoustic_optic_depth_fusion_frontend.hpp"
#include "frontends/loop_closure_frontend.hpp"
#include "frontends/sonar_cfar_frontend.hpp"
#include "frontends/stereo_landmark_vo_frontend.hpp"
#include "frontends/stereo_optical_depth_frontend.hpp"
#include "mapping/acoustic_optic_map_bridge.hpp"
#include "mapping/submap_manager.hpp"
#include "opencv_adapters/stereo_rectifier.hpp"
#include "runtime/acoustic_optic_synchronizer.hpp"
#include "runtime/config.hpp"
#include "runtime/mcap_event_source.hpp"
#include "runtime/run_manifest.hpp"
#include "sensor_models/geometry.hpp"
#include "sensor_models/sonar_beam_model.hpp"

using uw::sensor_models::Pose3;

namespace {

std::string ToTumLine(double timestamp_s, const Pose3& pose) {
  std::ostringstream out;
  out.precision(9);
  out << timestamp_s << " " << pose.translation.x() << " " << pose.translation.y() << " "
      << pose.translation.z() << " " << pose.rotation.x() << " " << pose.rotation.y() << " "
      << pose.rotation.z() << " " << pose.rotation.w();
  return out.str();
}

// RunManifest population helpers (docs/uw-slam-production-readiness-and-
// roadmap-2026-08-21.md section 5.6: these fields were all silently empty
// before). Kept deliberately simple — no new dependency pulled in just to
// fill provenance metadata.

std::string NowIso8601Utc() {
  const auto now = std::chrono::system_clock::now();
  const std::time_t now_c = std::chrono::system_clock::to_time_t(now);
  std::tm utc_tm{};
  gmtime_r(&now_c, &utc_tm);
  std::ostringstream out;
  out << std::put_time(&utc_tm, "%Y-%m-%dT%H:%M:%SZ");
  return out.str();
}

// Not a cryptographic hash — just enough to detect "this config/calibration
// file's bytes changed since a prior run" for manifest provenance, not to
// resist tampering.
std::string Fnv1aHex(const std::string& data) {
  uint64_t hash = 1469598103934665603ull;  // FNV offset basis
  for (unsigned char c : data) {
    hash ^= c;
    hash *= 1099511628211ull;  // FNV prime
  }
  std::ostringstream out;
  out << std::hex << hash;
  return out.str();
}

std::string ReadFileBytesOrEmpty(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return "";
  std::ostringstream buffer;
  buffer << in.rdbuf();
  return buffer.str();
}

std::string DetectOsInfo() {
  struct utsname info{};
  if (uname(&info) != 0) return "unknown";
  return std::string(info.sysname) + " " + info.release + " " + info.machine;
}

// Linux-specific (this codebase's dev/CI environment per CLAUDE.md); a
// non-Linux build just gets "unknown" rather than failing to compile.
std::string DetectCpuInfo() {
  std::ifstream cpuinfo("/proc/cpuinfo");
  std::string line;
  while (std::getline(cpuinfo, line)) {
    const auto colon = line.find(':');
    if (colon != std::string::npos && line.compare(0, 10, "model name") == 0) {
      std::string value = line.substr(colon + 1);
      const auto first = value.find_first_not_of(' ');
      return first == std::string::npos ? "unknown" : value.substr(first);
    }
  }
  return "unknown";
}

}  // namespace

uw::domain::StateSnapshot::TrackingStatus uw::application::DecideTrackingStatus(
    const ReplayTrackingInputs& inputs) {
  if (inputs.vo_enabled && inputs.vo_health == uw::domain::HealthReport::STATUS_UNAVAILABLE) {
    return uw::domain::StateSnapshot::TRACKING_STATUS_LOST;
  }
  if (!inputs.solver_converged ||
      (inputs.vo_enabled && inputs.vo_health == uw::domain::HealthReport::STATUS_SUSPECT)) {
    return uw::domain::StateSnapshot::TRACKING_STATUS_DEGRADED;
  }
  return uw::domain::StateSnapshot::TRACKING_STATUS_TRACKING;
}

uw::domain::StateSnapshot uw::application::BuildStateSnapshot(const StateSnapshotInputs& inputs) {
  uw::domain::StateSnapshot snapshot;
  snapshot.mutable_state_id()->set_value(inputs.state_id);
  snapshot.mutable_state_version()->set_value(inputs.state_version);
  *snapshot.mutable_capture_timestamp() = inputs.capture_timestamp;
  *snapshot.mutable_pose_wb() = inputs.pose.ToProto();
  snapshot.set_tracking_status(inputs.tracking_status);
  snapshot.mutable_calibration_version()->set_value(inputs.calibration_version);

  std::vector<std::string> evidence_values;
  evidence_values.reserve(inputs.contributing_evidence.size());
  for (const auto& id : inputs.contributing_evidence) evidence_values.push_back(id.value());
  std::sort(evidence_values.begin(), evidence_values.end());
  evidence_values.erase(std::unique(evidence_values.begin(), evidence_values.end()),
                        evidence_values.end());
  for (const auto& value : evidence_values) snapshot.add_contributing_measurements()->set_value(value);
  return snapshot;
}

uw::application::MapContributionCounts uw::application::CountDepthContributions(
    const uw::domain::FusedDepthMeasurement& fused) {
  MapContributionCounts counts;
  for (unsigned char byte : fused.contribution_mask()) {
    if (byte == static_cast<unsigned char>(uw::domain::DEPTH_CONTRIBUTION_OPTICAL_ONLY)) {
      ++counts.optical_only_points;
    } else if (byte == static_cast<unsigned char>(uw::domain::DEPTH_CONTRIBUTION_ACOUSTIC_OPTIC)) {
      ++counts.acoustic_optic_points;
    }
  }
  return counts;
}

std::vector<std::string> uw::application::EvaluateReplayGates(
    const uw::runtime::PlatformDefaultsConfig& defaults, const uw::estimation::GaussNewtonSummary& solver,
    const uw::evaluation::AteResult& ate, int num_landmarks, const MapContributionCounts& contributions,
    int num_acoustic_optic_accepted) {
  std::vector<std::string> failures;
  if (defaults.require_converged && !solver.converged) {
    failures.push_back("solver did not converge (" + std::to_string(solver.iterations) +
                       " iterations, stalled)");
  }
  if (defaults.min_matched_ate_poses > 0 &&
      static_cast<int>(ate.num_matched_poses) < defaults.min_matched_ate_poses) {
    failures.push_back("matched ATE poses " + std::to_string(ate.num_matched_poses) + " < required " +
                       std::to_string(defaults.min_matched_ate_poses));
  }
  if (defaults.max_ate_rmse_m >= 0.0 && ate.rmse_m > defaults.max_ate_rmse_m) {
    failures.push_back("ATE rmse " + std::to_string(ate.rmse_m) + "m > max " +
                       std::to_string(defaults.max_ate_rmse_m) + "m");
  }
  const uint64_t total_map_points = contributions.optical_only_points + contributions.acoustic_optic_points;
  if (defaults.require_nonempty_map && (static_cast<uint64_t>(num_landmarks) + total_map_points) == 0) {
    failures.push_back("map is empty (0 landmarks discovered, 0 map evidence points)");
  }
  if (defaults.min_acoustic_optic_accepted > 0 &&
      num_acoustic_optic_accepted < defaults.min_acoustic_optic_accepted) {
    failures.push_back("acoustic-optic accepted associations " +
                       std::to_string(num_acoustic_optic_accepted) + " < required " +
                       std::to_string(defaults.min_acoustic_optic_accepted));
  }
  if (defaults.min_acoustic_optic_map_points > 0 &&
      contributions.acoustic_optic_points < static_cast<uint64_t>(defaults.min_acoustic_optic_map_points)) {
    failures.push_back("acoustic-optic map points " + std::to_string(contributions.acoustic_optic_points) +
                       " < required " + std::to_string(defaults.min_acoustic_optic_map_points));
  }
  return failures;
}

uw::frontends::SonarCfarFrontendParams uw::application::BuildSonarCfarFrontendParams(
    const uw::runtime::SonarFrontendConfig& config) {
  uw::frontends::SonarCfarFrontendParams params;
  params.cfar.num_training_cells = config.training_cells;
  params.cfar.num_guard_cells = config.guard_cells;
  params.cfar.probability_false_alarm = config.probability_false_alarm;
  params.detector_threshold = static_cast<uint8_t>(config.detector_threshold);
  params.dbscan_eps_m = config.dbscan_eps_m;
  params.dbscan_min_samples = config.dbscan_min_samples;
  params.default_range_sigma_m = config.default_range_sigma_m;
  params.default_bearing_sigma_rad = config.default_bearing_sigma_rad;
  return params;
}

int uw::application::RunReplayPipeline(const ReplayOptions& opt,
                                       const std::string& git_commit) {
  if (opt.bag_path.empty()) {
    std::cerr << "replay pipeline requires a bag path\n";
    return 1;
  }
  const std::string run_start_time_iso8601 = NowIso8601Utc();
  // Layer 1: platform defaults (either from --experiment's defaults: layer,
  // or this struct's built-in values — same numbers previously hardcoded
  // as kRelativePoseSqrtInfo etc. below, now factored out to
  // uw::runtime::PlatformDefaultsConfig so they have exactly one
  // definition, in configs/defaults/platform.yaml).
  uw::runtime::PlatformDefaultsConfig defaults;
  bool write_run_manifest = true;
  // Only set when --experiment loads a rig with cameras — gates the new
  // acoustic-optic pass below so the no-experiment path (used by
  // tests/l2_replay/determinism_test.sh) is provably unchanged.
  std::optional<uw::domain::RigCalibrationSnapshot> rig;
  // Was read-but-unused before stereo_landmark_vo_frontend (see README's
  // "已知边界" — experiment's frontend/estimator/map-backend selection
  // fields didn't actually dispatch on anything). "stereo_landmark_vo"
  // is the first value that does: it switches the relative-pose block
  // below from synth_bag_gen's ground-truth+noise "black-box VIO" bag
  // evidence to real evidence computed from /raw/camera/left,right — see
  // that block for why this needs `rig` too, not just this string.
  std::string estimator_mode = "black_box_vio";
  std::string landmark_detector = "bright_blob";
  // RunManifest provenance (section 5.6): best-effort, not a guarantee — the
  // seed reflects this experiment's declared scenario seed, which is what
  // would generate a matching bag via synth_bag_gen, but a bag supplied from
  // elsewhere (e.g. a real HoloOcean recording) may not have come from it.
  uint64_t scenario_seed = 0;
  std::string config_hash;
  std::string calibration_hash;
  if (!opt.experiment_path.empty()) {
    const auto config = uw::runtime::LoadExperimentConfig(opt.experiment_path);
    if (const auto error = uw::runtime::ValidateExperimentConfigSelections(config)) {
      std::cerr << "invalid experiment config " << opt.experiment_path << ": " << *error << "\n";
      return 1;
    }
    defaults = config.defaults;
    write_run_manifest = config.write_run_manifest;
    if (config.rig.cameras_size() > 0) rig = config.rig;
    estimator_mode = config.estimator_mode;
    landmark_detector = config.landmark_detector;
    scenario_seed = config.scenario.seed;
    config_hash = Fnv1aHex(ReadFileBytesOrEmpty(opt.experiment_path));
    calibration_hash = Fnv1aHex(config.rig.SerializeAsString());
    std::cout << "loaded experiment config: " << opt.experiment_path << " (sonar_frontend="
              << config.sonar_frontend << ", estimator_mode=" << config.estimator_mode << ")\n";
  }
  if (opt.max_iterations > 0) defaults.max_iterations = opt.max_iterations;  // CLI wins last

  // Single ordered pass over the bag (docs/superpowers/plans/2026-08-24-
  // live-replay-unified-ingress.md Task 4): every ReadMcapMessages<T> call
  // this function used to make per-topic, per-payload-type is now a filter
  // over this one ReplayInputData -- see each consumption point below for
  // how its original filter is reproduced on the flattened vectors.
  uw::runtime::McapEventSource event_source(opt.bag_path);
  uw::application::ReplayInputAccumulator accumulator;
  const auto pump_report = uw::application::PumpEvents(event_source, accumulator);
  if (pump_report.status == uw::runtime::EventSourceStatus::kOpenFailed) {
    std::cerr << "failed to open bag: " << opt.bag_path << "\n";
    return 1;
  }
  if (pump_report.unknown_topic_count > 0 || pump_report.parse_failure_count > 0) {
    std::cout << "warning: bag scan saw " << pump_report.unknown_topic_count
              << " unknown-topic message(s) and " << pump_report.parse_failure_count
              << " topic/schema-mismatched message(s) (see EventSourceReport)\n";
  }
  if (accumulator.Diagnostics().HasErrors()) {
    std::cerr << "replay input identity error(s):\n";
    for (const auto& message : accumulator.Diagnostics().messages) std::cerr << "  - " << message << "\n";
    return 1;
  }
  const uw::application::ReplayInputData& input = accumulator.Data();

  // Rectify once, up front: everything downstream that consumes camera
  // frames (stereo_landmark_vo_frontend, stereo_optical_depth_frontend, and
  // therefore the acoustic-optic fusion/map-bridge chain built on top of it)
  // now hard-requires is_rectified()==true input (StereoGeometry::Resolve's
  // rectified-pair contract — see sensor_models/camera_model.hpp). A failed
  // Create() here means this rig cannot be rectified at all, so every
  // camera-dependent pass below would silently produce zero evidence;
  // failing the whole run immediately is more honest than that.
  std::optional<uw::opencv_adapters::StereoRectificationContext> rectification_context;
  if (rig.has_value()) {
    uw::opencv_adapters::StereoRectificationParams rectification_params;
    rectification_params.alpha = defaults.stereo_rectification.alpha;
    rectification_params.rectified_frame_suffix = defaults.stereo_rectification.frame_suffix;
    rectification_params.crop_policy =
        defaults.stereo_rectification.crop_policy == "common_valid_roi"
            ? uw::opencv_adapters::RectificationCropPolicy::kCommonValidRoi
            : uw::opencv_adapters::RectificationCropPolicy::kFullCanvas;
    std::string rectification_error;
    rectification_context = uw::opencv_adapters::StereoRectificationContext::Create(
        *rig, rectification_params, &rectification_error);
    if (!rectification_context.has_value()) {
      std::cerr << "stereo rectification failed: " << rectification_error << "\n";
      return 1;
    }
  }

  // Warmup window (defaults.warmup_seconds, 0 = disabled): translate to a
  // keyframe-count cutoff using synth_bag_gen's fixed 5 Hz keyframe spacing
  // ("kf0", "kf1", ... one every kKeyframeIntervalS). This is the one place
  // left in this file that still assumes that naming/spacing convention —
  // every other keyframe identity below comes straight from
  // ReplayInputData (wire observation ids), never from time. Keyframes
  // inside the window still
  // enter the graph and still get relative-pose (dead-reckoning) factors —
  // dead reckoning through the warmup period is exactly what a real
  // estimator keeps doing while it isn't yet trusting absolute corrections
  // — but they do NOT get sonar-range or depth factors (the two "absolute
  // reference" factor types below skip them). This is the batch-pose-graph
  // analogue of "don't fuse absolute fixes until the VIO's bias has settled"
  // (see defaults.warmup_seconds' doc comment in runtime/include/uw/
  // runtime/config.hpp for where the idea came from).
  //
  // kf0 stays the fixed anchor regardless of warmup_seconds: re-anchoring
  // to a later keyframe would require knowing that keyframe's true x/y/yaw,
  // which nothing in this graph observes (x/y/yaw are genuine gauge freedom
  // — see below) — only kf0 gets to use Identity() for those because
  // synth_bag_gen places kf0 at the world-frame origin by construction, not
  // because "first keyframe" is special in general.
  constexpr double kKeyframeIntervalS = 0.2;  // matches synth_bag_gen's 5 Hz spacing
  const int warmup_keyframes = defaults.warmup_seconds > 0.0
                                    ? static_cast<int>(std::ceil(defaults.warmup_seconds / kKeyframeIntervalS))
                                    : 0;
  std::unordered_set<std::string> warmup_keyframe_ids;
  for (int i = 0; i < warmup_keyframes; ++i) warmup_keyframe_ids.insert("kf" + std::to_string(i));
  if (warmup_keyframes > 0) {
    std::cout << "warmup_seconds=" << defaults.warmup_seconds << " -> " << warmup_keyframes
              << " keyframes dead-reckoned only (no sonar/depth fusion)\n";
  }

  // Gauge choice for the fixed anchor keyframe "kf0": x/y/yaw are genuine
  // gauge freedom for a relative-pose + range-only graph (nothing observes
  // an absolute horizontal position or heading), so identity is a fine
  // arbitrary choice for those. z is NOT gauge freedom once a depth factor
  // is in the graph — the depth sensor gives every keyframe (including
  // kf0) an absolute reference. Fixing kf0's z at 0 while depth factors
  // pull every other keyframe toward -measured_depth creates a genuine
  // constraint conflict (this was found by running the demo: the solver
  // stalled and ATE was several meters, not the sub-decimeter error a
  // clean synthetic scenario with this little noise should produce).
  // Anchoring kf0's z from its own depth measurement keeps the fixed
  // keyframe consistent with the rest of the graph — this is independent of
  // warmup_seconds: it directly seeds the fixed vertex rather than adding a
  // depth factor, so it's not one of the "fusions" warmup gates.
  double kf0_z = 0.0;
  for (const auto& evidence : input.evidence) {
    if (kf0_z != 0.0) break;  // already found
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    if (evidence.source_observations(0).value() != "kf0") continue;
    // depth_m is positive-down (world Z-up); negate to get pose z — see
    // PressureDepthMeasurement's field comment in
    // schemas/proto/uw/domain/measurement.proto.
    kf0_z = -uw::domain::GetPayload<uw::domain::PressureDepthMeasurement>(evidence).depth_m();
  }

  uw::estimation::PoseGraphProblem problem;
  Pose3 kf0_pose = Pose3::Identity();
  kf0_pose.translation.z() = kf0_z;
  problem.AddKeyframe("kf0", kf0_pose, /*fixed=*/true);

  // sqrt-information constants, from configs/defaults/platform.yaml via
  // --experiment (or PlatformDefaultsConfig's built-in fallback values if
  // --experiment wasn't passed). See file header limitation note: these
  // are still fixed constants, not a calibrated reliability scheduler.
  const double relative_pose_translation_cap = defaults.default_sqrt_information.relative_pose.translation;
  const double relative_pose_rotation_cap = defaults.default_sqrt_information.relative_pose.rotation;
  // FactorCandidate.proposed_noise is a single wire scalar (see
  // RelativePoseFactorBuilder::Build()'s own comment) -- set it to the max
  // of the two typed caps so it never tightens either one below what the
  // builder itself was already constructed with.
  const double relative_pose_sqrt_info = std::max(relative_pose_translation_cap, relative_pose_rotation_cap);
  const double sonar_range_sqrt_info = defaults.default_sqrt_information.sonar_range;
  const double depth_sqrt_info = defaults.default_sqrt_information.depth;

  uw::factor_builders::RelativePoseFactorBuilder relative_pose_builder(relative_pose_translation_cap,
                                                                       relative_pose_rotation_cap);
  uw::factor_builders::SonarRangeFactorBuilder sonar_range_builder;
  uw::factor_builders::DepthFactorBuilder depth_builder;

  // Online landmark store for the sonar range factor's data association
  // (see file header). All discovered landmarks live in one "landmarks"
  // bucket at a fixed Identity pose, since QueryNearestPoint/
  // WorldPointsForKeyframe already store/return world-frame points — see
  // include/mapping/submap_manager.hpp. Declared here (not down by
  // StateStore below) because it needs to be live during the sonar
  // evidence pass, not just after solving.
  uw::mapping::SubmapManager submap_manager;
  submap_manager.UpdateKeyframePose("landmarks", Pose3::Identity());
  int next_landmark_id = 0;
  int num_landmarks_discovered = 0;

  // Camera frames, partitioned once and shared by both the relative-pose
  // block below (estimator_mode == "stereo_landmark_vo") and the acoustic-
  // optic pass further down — both used to read these topics independently
  // before this migration. Frames stay RAW here: the synchronizer and sonar
  // frontend still consume raw sonar/raw image headers (capture_time,
  // sensor_frame) per this file's acoustic-optic pass, only the rectified/
  // MONO8 pixel content is derived on demand below via get_rectified().
  //
  // Identity comes straight from header.observation_id (ImageFrame.header,
  // set by synth_bag_gen's BuildStereoPair / record_session.py's
  // _write_keyframe) — no capture_time-based reconstruction. left/right are
  // told apart by header.sensor_id ("camera_left"/"camera_right"), the same
  // convention both producers already use.
  std::unordered_map<std::string, uw::domain::ImageFrame> left_by_kf_raw, right_by_kf_raw;
  // First-appearance order of camera keyframe ids, in the bag's log_time_ns
  // order (McapEventSource) — replaces the old "kf" + std::to_string(i) for
  // i in [0, max_kf_index] loop, which assumed contiguous numeric ids.
  std::vector<std::string> ordered_camera_keyframe_ids;
  std::unordered_set<std::string> seen_camera_keyframe_ids;

  // Real per-keyframe metadata for StateSnapshot/TUM output (P1: no more
  // `index * kKeyframeIntervalS` timestamp fabrication). Priority for
  // capture_time_by_keyframe, highest first: raw left camera capture_time
  // (set here) > /gt/state's own capture_timestamp, matched by state_id
  // (set below, before the snapshot loop) > the MCAP log_time_ns of
  // whatever relative-pose/depth evidence first referenced this keyframe
  // (set in those read passes below) -- each tier only fills a keyframe
  // that a higher tier left unset.
  std::unordered_map<std::string, uw::domain::Stamp> capture_time_by_keyframe;
  std::unordered_map<std::string, std::vector<uw::domain::EvidenceId>> evidence_by_keyframe;

  if (rig.has_value()) {
    for (const auto& frame : input.images) {
      const std::string& kf_id = frame.header().observation_id().value();
      const std::string& sensor_id = frame.header().sensor_id().value();
      if (sensor_id == "camera_left") {
        left_by_kf_raw[kf_id] = frame;
        capture_time_by_keyframe[kf_id] = frame.header().capture_time();
      } else if (sensor_id == "camera_right") {
        right_by_kf_raw[kf_id] = frame;
      } else {
        continue;
      }
      if (seen_camera_keyframe_ids.insert(kf_id).second) ordered_camera_keyframe_ids.push_back(kf_id);
    }
  }

  // Rectifies (ConvertToMono8 + StereoRectificationContext::Process()) a
  // keyframe's raw stereo pair at most once, caching the result so the VO
  // pass and the acoustic-optic pass below never remap the same pixels
  // twice. Returns nullptr if the raw pair is missing or fails
  // ConvertToMono8/Process() (e.g. wrong encoding, size mismatch) — a
  // per-keyframe condition, not a fatal error like a failed Create() above.
  std::unordered_map<std::string, uw::opencv_adapters::RectifiedStereoBundle> rectified_by_kf;
  auto get_rectified = [&](const std::string& kf_id) -> uw::opencv_adapters::RectifiedStereoBundle* {
    const auto cached = rectified_by_kf.find(kf_id);
    if (cached != rectified_by_kf.end()) return &cached->second;
    const auto left_it = left_by_kf_raw.find(kf_id);
    const auto right_it = right_by_kf_raw.find(kf_id);
    if (left_it == left_by_kf_raw.end() || right_it == right_by_kf_raw.end()) return nullptr;
    const auto left_mono = uw::domain::ConvertToMono8(left_it->second);
    const auto right_mono = uw::domain::ConvertToMono8(right_it->second);
    if (!left_mono.has_value() || !right_mono.has_value()) return nullptr;
    std::string process_error;
    auto rectified = rectification_context->Process(*left_mono, *right_mono, &process_error);
    if (!rectified.has_value()) return nullptr;
    return &rectified_by_kf.emplace(kf_id, std::move(*rectified)).first->second;
  };

  // Per-keyframe VO health AT THE TIME that keyframe was processed --
  // black-box mode never populates this (no local VO frontend to ask), so
  // DecideTrackingStatus's vo_enabled must be false for those snapshots.
  std::unordered_map<std::string, uw::domain::HealthReport::Status> vo_health_by_keyframe;

  // Fills the remaining capture_time_by_keyframe priority tiers below raw
  // camera capture_time (already set above, unconditionally, when it
  // exists): GT's own real capture_timestamp (matched by state_id -- a
  // genuine timestamp field this platform's synthetic/real bags already
  // carry, used here for TIMING only, never for pose -- ground truth still
  // never enters estimated state), then the MCAP log_time_ns of whichever
  // depth/relative-pose evidence first referenced a keyframe, as a last
  // resort. .emplace() only inserts when a higher tier hasn't already
  // claimed that keyframe, so running these three passes in this fixed
  // order IS the priority order.
  std::vector<uw::evaluation::TrajectoryPose> ground_truth_trajectory;
  for (const auto& gt : input.reference_states) {
    if (gt.has_state_id() && !gt.state_id().value().empty()) {
      capture_time_by_keyframe.emplace(gt.state_id().value(), gt.capture_timestamp());
    }
    ground_truth_trajectory.push_back(
        {uw::domain::ToSeconds(gt.capture_timestamp()), Pose3::FromProto(gt.pose_wb())});
  }
  int num_timestamp_fallback_evidence = 0;
  for (std::size_t i = 0; i < input.evidence.size(); ++i) {
    const auto& evidence = input.evidence[i];
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    const auto log_time_ns = accumulator.EvidenceLogTimeNs()[i];
    const auto [it, inserted] = capture_time_by_keyframe.emplace(
        evidence.source_observations(0).value(),
        uw::domain::FromSeconds(static_cast<double>(log_time_ns) * 1e-9));
    if (inserted) ++num_timestamp_fallback_evidence;
  }
  for (std::size_t i = 0; i < input.evidence.size(); ++i) {
    const auto& evidence = input.evidence[i];
    if (!uw::domain::HasPayload<uw::domain::RelativePoseMeasurement>(evidence)) continue;
    const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(evidence);
    const auto log_time_ns = accumulator.EvidenceLogTimeNs()[i];
    const auto [it, inserted] = capture_time_by_keyframe.emplace(
        measurement.to_keyframe().value(), uw::domain::FromSeconds(static_cast<double>(log_time_ns) * 1e-9));
    if (inserted) ++num_timestamp_fallback_evidence;
  }
  if (num_timestamp_fallback_evidence > 0) {
    std::cout << "warning: " << num_timestamp_fallback_evidence
              << " keyframe(s) had no camera/GT timestamp; used MCAP log_time_ns as a fallback\n";
  }

  int num_relative_pose_factors = 0;
  if (rig.has_value() && estimator_mode == "stereo_landmark_vo") {
    // Real relative-pose evidence computed from stereo camera frames
    // (include/frontends/stereo_landmark_vo_frontend.hpp) instead of
    // synth_bag_gen's ground-truth+noise "black-box VIO" stand-in read
    // from /evidence/relative_pose below. Keyframes must be visited in
    // order (the frontend is stateful across calls, comparing this call's
    // landmarks to the previous one's) — iterate kf0..kfN in order rather
    // than relying on bag stream order.
    uw::frontends::StereoLandmarkVoFrontendParams vo_params;
    vo_params.left_frame = rectification_context->LeftRectifiedFrame();
    vo_params.right_frame = rectification_context->RightRectifiedFrame();
    vo_params.max_consecutive_failures = defaults.visual_odometry.max_consecutive_failures;
    vo_params.covariance_estimation.max_condition_number = defaults.visual_odometry.max_condition_number;
    vo_params.covariance_estimation.residual_variance_floor_m2 =
        defaults.visual_odometry.residual_variance_floor_m2;
    vo_params.covariance_estimation.max_inlier_rmse_m = defaults.visual_odometry.max_inlier_rmse_m;
    vo_params.detector_kind = landmark_detector == "harris_corner"
                                   ? uw::frontends::LandmarkDetectorKind::kHarrisCorner
                                   : uw::frontends::LandmarkDetectorKind::kBrightBlob;
    if (landmark_detector == "harris_corner") {
      // Only for the real-camera path: synth_bag_gen's landmarks are
      // deliberately unique per-id hash patterns (see its header), so
      // PatchMatcher's plain greedy NCC never had an ambiguity problem
      // there and the tracked synthetic ATE number shouldn't shift.
      // Real underwater imagery (coral/rock/sand) is locally repetitive —
      // confirmed the hard way running apps/replay_demo against a real
      // HoloOcean recording: appearance-only matching with no
      // spatial/distinctiveness constraint produced ATE=587m (solver
      // stalled), because RANSAC's majority-consensus assumption breaks
      // down once wrong correspondences are as numerous as right ones.
      // max_row_diff_px mirrors BlockMatcher's own same-row disparity
      // search (an epipolar constraint for this rig's parallel stereo
      // pair); min_score_margin rejects a match unless it is clearly
      // better than the next-best candidate for either side (a
      // Lowe's-ratio-test-style distinctiveness check) — see
      // patch_matcher.hpp for both. Thresholds are a first empirical pass
      // against the one real bag available, not a calibrated constant.
      vo_params.stereo_matcher.max_row_diff_px = 4.0;
      vo_params.stereo_matcher.min_score_margin = 0.02;
      vo_params.temporal_matcher.min_score_margin = 0.05;
    }
    uw::frontends::StereoLandmarkVoFrontend vo_frontend(vo_params);

    for (const auto& kf_id : ordered_camera_keyframe_ids) {
      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;

      uw::measurement_api::CameraFrameBundle bundle = rectified->images;
      bundle.primary.mutable_header()->mutable_observation_id()->set_value(kf_id);

      const auto vo_evidence = vo_frontend.Process(bundle, rectification_context->DerivedRig());
      // Recorded for EVERY processed frame, success or failure, keyed by
      // the frame that was just processed -- this is what makes
      // DecideTrackingStatus's per-snapshot VO health non-retroactive (a
      // keyframe processed while VO was still healthy must stay TRACKING
      // even if VO later degrades).
      vo_health_by_keyframe[kf_id] = vo_frontend.Health().status();
      if (!vo_evidence.has_value()) continue;  // first frame seen, or couldn't fit this transition

      const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(*vo_evidence);
      const std::string from = measurement.from_keyframe().value();
      const std::string to = measurement.to_keyframe().value();
      if (!problem.HasKeyframe(from)) continue;  // out-of-order/unexpected input: skip, don't guess

      const auto measured_relative = Pose3::FromProto(measurement.relative_pose());
      const auto dead_reckoned_initial_guess = problem.GetKeyframePose(from) * measured_relative;
      problem.AddKeyframe(to, dead_reckoned_initial_guess);

      uw::domain::FactorCandidate candidate;
      candidate.set_residual_model(uw::factor_builders::RelativePoseFactorBuilder::kResidualModel);
      candidate.set_proposed_noise(relative_pose_sqrt_info);
      auto block = relative_pose_builder.Build(candidate, *vo_evidence, {});
      if (block) {
        problem.AddResidualBlock(std::move(block), {from, to});
        evidence_by_keyframe[to].push_back(vo_evidence->evidence_id());
        ++num_relative_pose_factors;
      }
    }
    std::cout << "stereo_landmark_vo_frontend: computed relative-pose evidence from camera frames "
                 "(estimator_mode=stereo_landmark_vo)\n";
  } else {
    for (const auto& evidence : input.evidence) {
      if (!uw::domain::HasPayload<uw::domain::RelativePoseMeasurement>(evidence)) continue;
      const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(evidence);
      const std::string from = measurement.from_keyframe().value();
      const std::string to = measurement.to_keyframe().value();
      if (!problem.HasKeyframe(from)) continue;  // out-of-order/unexpected input: skip, don't guess

      const auto measured_relative = Pose3::FromProto(measurement.relative_pose());
      const auto dead_reckoned_initial_guess = problem.GetKeyframePose(from) * measured_relative;
      problem.AddKeyframe(to, dead_reckoned_initial_guess);

      uw::domain::FactorCandidate candidate;
      candidate.set_residual_model(uw::factor_builders::RelativePoseFactorBuilder::kResidualModel);
      candidate.set_proposed_noise(relative_pose_sqrt_info);
      auto block = relative_pose_builder.Build(candidate, evidence, {});
      if (block) {
        problem.AddResidualBlock(std::move(block), {from, to});
        evidence_by_keyframe[to].push_back(evidence.evidence_id());
        ++num_relative_pose_factors;
      }
    }
  }
  std::cout << "added " << num_relative_pose_factors << " relative-pose factors, "
            << problem.NumKeyframes() << " keyframes\n";

  // Loop-closure pose-graph edges (architecture-inspired by SVIn's
  // pose_graph module — see frontends/loop_closure_frontend.hpp's own
  // header comment for what was and wasn't ported). A second pass, AFTER
  // the stereo_landmark_vo loop above has finished dead-reckoning every
  // keyframe into `problem` — not interleaved with it — so "advance dead
  // reckoning one edge at a time" and "search the whole archive so far"
  // stay separate concerns and the archive never contains a not-yet-
  // dead-reckoned keyframe. Gated by the SAME rig/estimator_mode
  // precondition as VO (loop closure needs real camera frames) plus
  // defaults.loop_closure.enabled (default off — zero behavior change to
  // any existing experiment unless a config explicitly opts in).
  int num_loop_closure_factors = 0;
  if (rig.has_value() && estimator_mode == "stereo_landmark_vo" && defaults.loop_closure.enabled) {
    uw::frontends::LoopClosureFrontendParams lc_params;
    lc_params.left_frame = rectification_context->LeftRectifiedFrame();
    lc_params.right_frame = rectification_context->RightRectifiedFrame();
    lc_params.candidate_search_radius_m = defaults.loop_closure.candidate_search_radius_m;
    lc_params.min_keyframe_index_gap = defaults.loop_closure.min_keyframe_index_gap;
    lc_params.max_accepted_translation_m = defaults.loop_closure.max_accepted_translation_m;
    lc_params.max_accepted_rotation_rad = defaults.loop_closure.max_accepted_rotation_rad;
    lc_params.min_landmarks_for_pose = defaults.loop_closure.min_landmarks_for_pose;
    lc_params.max_loop_edges_per_keyframe = defaults.loop_closure.max_loop_edges_per_keyframe;
    uw::frontends::LoopClosureFrontend loop_frontend(lc_params);

    for (const auto& kf_id : ordered_camera_keyframe_ids) {
      if (!problem.HasKeyframe(kf_id)) continue;  // VO never dead-reckoned this one (e.g. the first frame)
      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;

      uw::measurement_api::CameraFrameBundle bundle = rectified->images;
      bundle.primary.mutable_header()->mutable_observation_id()->set_value(kf_id);

      // problem.GetKeyframePose(kf_id) here is still the PRE-SOLVE
      // dead-reckoned estimate (solver.Solve() hasn't run yet) — exactly
      // the "position at insertion time" pose-proximity search needs.
      const auto loop_evidences =
          loop_frontend.Process(bundle, rectification_context->DerivedRig(), kf_id, problem.GetKeyframePose(kf_id));
      for (const auto& loop_evidence : loop_evidences) {
        const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(loop_evidence);
        const std::string from = measurement.from_keyframe().value();
        const std::string to = measurement.to_keyframe().value();
        if (!problem.HasKeyframe(from) || !problem.HasKeyframe(to)) continue;

        uw::domain::FactorCandidate candidate;
        candidate.set_residual_model(uw::factor_builders::RelativePoseFactorBuilder::kResidualModel);
        candidate.set_proposed_noise(relative_pose_sqrt_info);
        candidate.set_robust_policy_hint(uw::domain::ROBUST_POLICY_HUBER);
        auto block = relative_pose_builder.Build(candidate, loop_evidence, {});
        if (block) {
          problem.AddResidualBlock(std::move(block), {from, to},
                                   uw::estimation::PoseGraphProblem::RobustPolicy::kHuber);
          evidence_by_keyframe[to].push_back(loop_evidence.evidence_id());
          ++num_loop_closure_factors;
        }
      }
    }
    std::cout << "loop_closure_frontend: added " << num_loop_closure_factors << " loop-closure factors\n";
  }

  const auto cfar_params =
      uw::application::BuildSonarCfarFrontendParams(defaults.sonar_frontend);
  uw::frontends::SonarCfarFrontend sonar_frontend(cfar_params);

  int num_sonar_frames = 0;
  int num_sonar_factors = 0;
  // Per-sonar-frame processing latency, mirroring
  // acoustic_optic_scenario_matrix.cpp's per-trial
  // timing pattern. This loop (not the stereo_landmark_vo loop above,
  // which only runs in VO mode, and not any single point elsewhere in this
  // multi-pass batch file) is the one genuinely per-keyframe frontend +
  // data-association + factor-building pass that runs in every experiment
  // config regardless of estimator_mode — the natural place for a first
  // latency proxy. This is groundwork, not real online latency:
  // replay_demo processes a whole bag in a few batch passes, so this
  // measures per-frame CPU cost within that batch, not capture-to-pose
  // latency in a live system, which requires an online scheduler.
  std::vector<double> sonar_frame_latencies_ms;
  for (const auto& frame : input.sonar_frames) {
    // RAII so every exit path below (the early `continue`s for warmup/
    // unknown-keyframe/no-detection included) gets timed, not just the
    // full-processing path — a reject decision still costs real time
    // in an online system.
    struct LatencyRecorder {
      std::vector<double>& out;
      std::chrono::steady_clock::time_point start;
      ~LatencyRecorder() {
        out.push_back(
            std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count());
      }
    } latency_recorder{sonar_frame_latencies_ms, std::chrono::steady_clock::now()};

    ++num_sonar_frames;
    const std::string keyframe_id = frame.header().observation_id().value();
    if (!problem.HasKeyframe(keyframe_id)) continue;
    if (warmup_keyframe_ids.count(keyframe_id)) continue;  // dead-reckoning only during warmup

    // v1 rule (schemas/proto/uw/domain/hypothesis.proto, see file
    // header): only the top-ranked (largest-cluster) candidate is
    // consumed. candidates(0) is a full MeasurementEvidence, not just
    // the payload — reuse it as-is rather than re-wrapping via
    // domain::TopCandidate<T>(), which would discard evidence_id/
    // algorithm_version for no benefit here.
    const auto hypothesis_set = sonar_frontend.ProcessSonarFrame(frame);
    if (hypothesis_set.candidates_size() == 0) continue;  // no detection above threshold
    const auto& evidence = hypothesis_set.candidates(0);
    if (!uw::domain::HasPayload<uw::domain::SonarRangeBearing>(evidence)) continue;
    const auto& measurement = uw::domain::GetPayload<uw::domain::SonarRangeBearing>(evidence);

    // Real submap_manager query (see file header): project the
    // detection into world frame using the keyframe's CURRENT
    // (dead-reckoned, not yet optimized) pose estimate, then ask the
    // submap for an already-known landmark within kLandmarkGateM. A
    // hit reuses that landmark's stored position (stable across
    // repeated sightings, not re-derived from this noisier single
    // detection); a miss means this is a never-before-seen landmark,
    // which gets inserted so later sightings can match it.
    const auto current_pose = problem.GetKeyframePose(keyframe_id);
    const Eigen::Vector3d local_detection(measurement.range_m() * std::cos(measurement.bearing_rad()),
                                           measurement.range_m() * std::sin(measurement.bearing_rad()),
                                           0.0);  // sonar has no elevation — see file header
    const Eigen::Vector3d predicted_point_W = current_pose.Apply(local_detection);

    constexpr double kLandmarkGateM = 1.5;  // margin over expected dead-reckoning drift at these ranges
    const auto existing = submap_manager.QueryNearestPoint(predicted_point_W, kLandmarkGateM);
    Eigen::Vector3d landmark_W;
    if (existing.has_value()) {
      landmark_W = *existing;
    } else {
      landmark_W = predicted_point_W;
      uw::domain::MapEvidence landmark_evidence;
      landmark_evidence.mutable_evidence_id()->set_value("landmark_" + std::to_string(next_landmark_id++));
      landmark_evidence.mutable_keyframe_id()->set_value("landmarks");
      landmark_evidence.mutable_local_frame()->set_value("world");
      landmark_evidence.set_representation_type(uw::domain::MAP_REPRESENTATION_POINT_CLOUD);
      landmark_evidence.set_reintegration_policy(
          uw::domain::MapEvidence::REINTEGRATION_POLICY_TRANSFORM_ONLY);
      std::string bytes(3 * sizeof(float), '\0');
      auto* raw = reinterpret_cast<float*>(bytes.data());
      raw[0] = static_cast<float>(landmark_W.x());
      raw[1] = static_cast<float>(landmark_W.y());
      raw[2] = static_cast<float>(landmark_W.z());
      landmark_evidence.set_geometry_or_occupancy(bytes);
      submap_manager.AddMapEvidence(landmark_evidence);
      ++num_landmarks_discovered;
    }

    uw::domain::FactorCandidate candidate;
    candidate.set_residual_model(uw::factor_builders::SonarRangeFactorBuilder::kResidualModel);
    candidate.set_proposed_noise(sonar_range_sqrt_info);
    uw::measurement_api::FactorBuildContext context;
    context.nearby_points_W = {landmark_W};
    auto block = sonar_range_builder.Build(candidate, evidence, context);
    if (block) {
      problem.AddResidualBlock(std::move(block), {keyframe_id});
      evidence_by_keyframe[keyframe_id].push_back(evidence.evidence_id());
      ++num_sonar_factors;
    }
  }
  std::cout << "discovered " << num_landmarks_discovered << " landmarks via submap query\n";
  std::cout << "processed " << num_sonar_frames << " sonar frames (sonar_cfar_frontend) -> "
            << num_sonar_factors << " sonar range factors\n";
  // Same P95 formula as acoustic_optic_scenario_matrix.cpp (nearest-rank,
  // no interpolation) — see this block's own comment above for scope.
  std::sort(sonar_frame_latencies_ms.begin(), sonar_frame_latencies_ms.end());
  const double p95_sonar_frame_latency_ms =
      sonar_frame_latencies_ms.empty()
          ? 0.0
          : sonar_frame_latencies_ms[static_cast<std::size_t>(0.95 * (sonar_frame_latencies_ms.size() - 1))];
  std::cout << "sonar frame processing latency: p95_ms=" << p95_sonar_frame_latency_ms << "\n";

  int num_depth_factors = 0;
  for (const auto& evidence : input.evidence) {
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    const std::string keyframe_id = evidence.source_observations(0).value();
    if (!problem.HasKeyframe(keyframe_id)) continue;
    if (warmup_keyframe_ids.count(keyframe_id)) continue;  // dead-reckoning only during warmup

    uw::domain::FactorCandidate candidate;
    candidate.set_residual_model(uw::factor_builders::DepthFactorBuilder::kResidualModel);
    candidate.set_proposed_noise(depth_sqrt_info);
    auto block = depth_builder.Build(candidate, evidence, {});
    if (block) {
      problem.AddResidualBlock(std::move(block), {keyframe_id});
      evidence_by_keyframe[keyframe_id].push_back(evidence.evidence_id());
      ++num_depth_factors;
    }
  }
  std::cout << "added " << num_depth_factors << " depth factors\n";

  // defaults.solver: "gauss_newton_v1" (default) or "ceres_v1" — see
  // docs/superpowers/specs/2026-08-23-solver-and-mapping-oss-adoption.md §7.
  // Already validated as one of these two by ValidateExperimentConfigSelections
  // above; a "ceres_v1" selection in a binary that wasn't built with
  // UW_BUILD_CERES_SOLVER is a fatal startup error here, not a silent
  // fallback to gauss_newton_v1 (see that doc's §8 error table).
  uw::estimation::GaussNewtonSummary summary;
  if (defaults.solver == "ceres_v1") {
#ifdef UW_HAVE_CERES_SOLVER
    uw::adapters::ceres_solver::CeresPoseGraphSolver ceres_solver;
    uw::adapters::ceres_solver::CeresSolverOptions ceres_options;
    ceres_options.max_iterations = defaults.max_iterations;
    summary = ceres_solver.Solve(problem, ceres_options);
#else
    std::cerr << "solver: ceres_v1 requested but this binary was not built with "
                 "UW_BUILD_CERES_SOLVER=ON\n";
    return 1;
#endif
  } else {
    uw::estimation::GaussNewtonSolver solver;
    uw::estimation::GaussNewtonSolver::Options solver_options;
    solver_options.max_iterations = defaults.max_iterations;
    solver_options.initial_lambda = defaults.initial_lambda;
    // Only affects RobustPolicy::kHuber-flagged bindings (loop-closure
    // edges above); harmless no-op when none exist.
    solver_options.huber_delta = defaults.loop_closure.huber_delta;
    summary = solver.Solve(problem, solver_options);
  }
  std::cout << "solver(" << defaults.solver << "): " << summary.iterations << " iterations, cost "
            << summary.initial_cost << " -> " << summary.final_cost
            << (summary.converged ? " (converged)" : " (stalled)") << "\n";

  // StateStore wiring (submap_manager was declared earlier — it's already
  // been accumulating landmark evidence since the sonar pass above).
  uw::estimation::StateStore state_store;
  std::vector<uw::evaluation::TrajectoryPose> estimated_trajectory;

  const std::string calibration_version_for_snapshot =
      rectification_context.has_value() ? rectification_context->DerivedRig().calibration_version().value()
                                        : "";
  const bool vo_enabled_for_tracking = rig.has_value() && estimator_mode == "stereo_landmark_vo";

  int num_snapshot_timestamp_missing = 0;
  for (int i = 0; i < static_cast<int>(problem.KeyframeOrder().size()); ++i) {
    const std::string& kf_id = problem.KeyframeOrder()[i];
    const auto pose = problem.GetKeyframePose(kf_id);

    uw::application::ReplayTrackingInputs tracking_inputs;
    tracking_inputs.solver_converged = summary.converged;
    tracking_inputs.vo_enabled = vo_enabled_for_tracking;
    const auto vo_health_it = vo_health_by_keyframe.find(kf_id);
    if (vo_health_it != vo_health_by_keyframe.end()) tracking_inputs.vo_health = vo_health_it->second;

    uw::application::StateSnapshotInputs snapshot_inputs;
    snapshot_inputs.state_id = kf_id;
    snapshot_inputs.state_version = static_cast<uint64_t>(i) + 1;
    snapshot_inputs.pose = pose;
    const auto capture_time_it = capture_time_by_keyframe.find(kf_id);
    if (capture_time_it != capture_time_by_keyframe.end()) {
      snapshot_inputs.capture_timestamp = capture_time_it->second;
    } else {
      ++num_snapshot_timestamp_missing;  // no camera/GT/evidence time at all: Stamp{} default (epoch)
    }
    snapshot_inputs.calibration_version = calibration_version_for_snapshot;
    const auto evidence_it = evidence_by_keyframe.find(kf_id);
    if (evidence_it != evidence_by_keyframe.end()) snapshot_inputs.contributing_evidence = evidence_it->second;
    snapshot_inputs.tracking_status = uw::application::DecideTrackingStatus(tracking_inputs);

    const auto snapshot = uw::application::BuildStateSnapshot(snapshot_inputs);
    state_store.Commit(snapshot);

    submap_manager.UpdateKeyframePose(kf_id, pose);
    estimated_trajectory.push_back({uw::domain::ToSeconds(snapshot.capture_timestamp()), pose});
  }
  if (num_snapshot_timestamp_missing > 0) {
    std::cout << "warning: " << num_snapshot_timestamp_missing
              << " keyframe(s) had no camera/GT/evidence timestamp at all; capture_timestamp defaults to "
                 "epoch\n";
  }

  // Acoustic-optic pass (only when --experiment loaded a rig with cameras):
  // per keyframe, run StereoOpticalDepthFrontend -> SonarCfarFrontend
  // (reused, same instance as the sonar pass above) ->
  // AcousticOpticDepthFusionFrontend::Fuse -> BuildMapEvidenceFromFusedDepth,
  // depositing a THIRD MapEvidence bucket into submap_manager (keyed per
  // keyframe, alongside the existing "landmarks" bucket) using the pose
  // ALREADY committed above. This never touches PoseGraphProblem/the solver
  // /ATE — dense depth does not become a new factor type.
  int num_keyframes_with_camera = 0;
  int num_acoustic_optic_accepted = 0;
  int num_acoustic_optic_ambiguous = 0;
  int num_acoustic_optic_conflict = 0;
  int num_acoustic_optic_rejected = 0;
  int num_sync_invalid_timestamp = 0;
  int num_map_evidence_points = 0;
  MapContributionCounts total_contributions;
  if (rig.has_value()) {
    // left_by_kf_raw / right_by_kf_raw / get_rectified are defined above,
    // shared with the relative-pose block's stereo_landmark_vo_frontend
    // path.
    std::unordered_map<std::string, uw::domain::SonarFrame> sonar_by_kf;
    for (const auto& f : input.sonar_frames) {
      // v1 top-1 rule (see file header): keep the first sonar frame seen
      // per keyframe if more than one target was in range.
      const std::string kf_id = f.header().observation_id().value();
      if (sonar_by_kf.find(kf_id) == sonar_by_kf.end()) sonar_by_kf[kf_id] = f;
    }

    uw::frontends::StereoOpticalDepthFrontendParams stereo_params;
    stereo_params.left_frame = rectification_context->LeftRectifiedFrame();
    stereo_params.right_frame = rectification_context->RightRectifiedFrame();
    stereo_params.matcher.min_texture_variance = defaults.stereo_matching.min_texture_variance;
    stereo_params.matcher.min_uniqueness_margin = defaults.stereo_matching.min_uniqueness_margin;
    stereo_params.matcher.left_right_max_diff_px = defaults.stereo_matching.left_right_max_diff_px;
    uw::frontends::StereoOpticalDepthFrontend stereo_frontend(stereo_params);
    uw::frontends::AcousticOpticDepthFusionParams fusion_params;
    uw::frontends::AcousticOpticDepthFusionFrontend fusion_frontend(fusion_params);
    uw::mapping::AcousticOpticMapBridgeParams bridge_params;

    for (std::size_t kf_index = 0; kf_index < problem.KeyframeOrder().size(); ++kf_index) {
      const std::string& kf_id = problem.KeyframeOrder()[kf_index];
      auto left_raw_it = left_by_kf_raw.find(kf_id);
      auto right_raw_it = right_by_kf_raw.find(kf_id);
      if (left_raw_it == left_by_kf_raw.end() || right_raw_it == right_by_kf_raw.end()) continue;
      ++num_keyframes_with_camera;

      const auto sonar_it = sonar_by_kf.find(kf_id);
      uw::runtime::SynchronizerParams sync_params;
      // The synchronizer and its downstream time_delta below still consume
      // RAW image headers (capture_time, sensor_frame) -- rectification
      // only changes pixel content/frame naming, not capture timing.
      const auto sync_decision = uw::runtime::SynchronizeAcousticOptic(
          left_raw_it->second, std::optional<uw::domain::ImageFrame>(right_raw_it->second),
          sonar_it != sonar_by_kf.end() ? std::optional<uw::domain::SonarFrame>(sonar_it->second)
                                        : std::nullopt,
          *rig, sync_params);

      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;
      const auto optical_evidence =
          stereo_frontend.Process(rectified->images, rectification_context->DerivedRig());
      if (!optical_evidence.has_value()) continue;

      // kSynchronized/kTimeDeltaExceeded both hand the REAL sonar hypothesis
      // and REAL delta to Fuse() -- the associator's own first-checked time
      // gate (frontends/acoustic_optic_associator.cpp) is what turns an
      // excessive delta into a REJECTED/TIME_DELTA record before any
      // geometric projection, so this file no longer needs to (and must
      // not) fake a zero delta to route around that decision. kNoSonar and
      // kInvalidTimestamp both fall through with an empty hypothesis set,
      // which makes Fuse() return a purely optical-only result with no
      // association record at all -- the optical chain never stops running
      // just because the cross-modal pairing did.
      uw::domain::HypothesisSet sonar_hypotheses;
      switch (sync_decision.status) {
        case uw::runtime::SynchronizationStatus::kSynchronized:
        case uw::runtime::SynchronizationStatus::kTimeDeltaExceeded:
          sonar_hypotheses = sonar_frontend.ProcessSonarFrame(sonar_it->second);
          break;
        case uw::runtime::SynchronizationStatus::kNoSonar:
          break;
        case uw::runtime::SynchronizationStatus::kInvalidTimestamp:
          ++num_sync_invalid_timestamp;
          break;
      }

      const auto fused_result =
          fusion_frontend.Fuse(sonar_hypotheses, *optical_evidence, rectification_context->DerivedRig(),
                                sync_decision.max_pairwise_time_delta_s);
      if (!fused_result.has_value()) continue;

      const auto& fused = uw::domain::GetPayload<uw::domain::FusedDepthMeasurement>(fused_result->fused_evidence);
      const auto contribution_counts = CountDepthContributions(fused);
      total_contributions.optical_only_points += contribution_counts.optical_only_points;
      total_contributions.acoustic_optic_points += contribution_counts.acoustic_optic_points;
      if (fused.associations_size() > 0) {
        switch (fused.associations(0).status()) {
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_ACCEPTED:
            ++num_acoustic_optic_accepted;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_AMBIGUOUS:
            ++num_acoustic_optic_ambiguous;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_CONFLICT:
            ++num_acoustic_optic_conflict;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_REJECTED:
            ++num_acoustic_optic_rejected;
            break;
          default:
            break;
        }
      }

      const uint64_t state_version = kf_index + 1;
      const auto map_evidence = uw::mapping::BuildMapEvidenceFromFusedDepth(
          fused_result->fused_evidence, rectification_context->DerivedRig(), bridge_params, kf_id,
          state_version);
      if (map_evidence.has_value()) {
        num_map_evidence_points +=
            static_cast<int>(map_evidence->geometry_or_occupancy().size() / (3 * sizeof(float)));
        submap_manager.AddMapEvidence(*map_evidence);
      }
    }
    std::cout << "acoustic-optic: " << num_keyframes_with_camera << " keyframes with camera data, "
              << num_acoustic_optic_accepted << " accepted, " << num_acoustic_optic_ambiguous
              << " ambiguous, " << num_acoustic_optic_conflict << " conflict, " << num_acoustic_optic_rejected
              << " rejected, " << num_sync_invalid_timestamp
              << " sync invalid-timestamp (optical-only), " << num_map_evidence_points
              << " map evidence points added (" << total_contributions.optical_only_points
              << " optical-only, " << total_contributions.acoustic_optic_points << " acoustic-optic)\n";
  }

  const auto ate =
      uw::evaluation::ComputeAte(estimated_trajectory, ground_truth_trajectory, 0.05, opt.align_ate);
  std::cout << "ATE: rmse=" << ate.rmse_m << "m mean=" << ate.mean_m << "m max=" << ate.max_m
            << "m (" << ate.num_matched_poses << " matched poses)\n";

  {
    std::ofstream traj_out(opt.out_prefix + "_trajectory.tum");
    for (const auto& pose_entry : estimated_trajectory) {
      traj_out << ToTumLine(pose_entry.timestamp_s, pose_entry.pose_WB) << "\n";
    }
  }

  if (write_run_manifest) {
    uw::runtime::RunManifest manifest;
    manifest.run_id = "replay_demo_" + std::to_string(
                                            std::chrono::duration_cast<std::chrono::seconds>(
                                                std::chrono::system_clock::now().time_since_epoch())
                                                .count());
    manifest.git_commit = git_commit;
    manifest.config_hash = config_hash;
    manifest.calibration_hash = calibration_hash;
    manifest.derived_calibration_hash =
        rectification_context.has_value()
            ? Fnv1aHex(rectification_context->DerivedRig().SerializeAsString())
            : "";
    manifest.dataset_or_scenario = opt.bag_path;
    manifest.simulator = "synthetic (apps/synth_bag_gen.cpp)";
    manifest.os_info = DetectOsInfo();
    manifest.cpu_info = DetectCpuInfo();
    manifest.gpu_info = "n/a (CPU-only Eigen pipeline, no GPU dependency in this build)";
    manifest.seed = scenario_seed;
    manifest.start_time_iso8601 = run_start_time_iso8601;
    manifest.end_time_iso8601 = NowIso8601Utc();
    std::ofstream manifest_out(opt.out_prefix + "_run_manifest.json");
    manifest_out << manifest.ToJson();
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum and " << opt.out_prefix
              << "_run_manifest.json\n";
  } else {
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum (run_manifest disabled by config)\n";
  }

  // P0 non-void gates (docs/uw-slam-production-readiness-and-roadmap-2026-
  // 08-21.md section 5.5): outputs above are always written for
  // diagnosability even on failure — only the exit code changes — so a CI
  // gate failure still leaves a trajectory/manifest to inspect. Each gate
  // is individually opt-in via defaults.*/experiment `gates:` (see
  // include/runtime/config.hpp) except require_converged, which defaults on
  // because a stalled solver is never an acceptable output.
  const std::vector<std::string> gate_failures =
      EvaluateReplayGates(defaults, summary, ate, num_landmarks_discovered, total_contributions,
                          num_acoustic_optic_accepted);
  if (!gate_failures.empty()) {
    std::cerr << "GATE FAILURE:\n";
    for (const auto& failure : gate_failures) std::cerr << "  - " << failure << "\n";
    return 2;
  }
  return 0;
}
